AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Stackery Serverless Cron Example Stack
Resources:
  functionAAE762EE:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-functionAAE762EE
      Description: !Sub
        - Stackery Stack ${StackeryStackTagName} Environment ${StackeryEnvironmentTagName} Function ${ResourceName}
        - ResourceName: myCronJob
      CodeUri: src/myCronJob
      Handler: StackeryFunction::StackeryFunction.Handler::handler
      Runtime: dotnetcore2.1
      MemorySize: 128
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
      Events:
        timerE0F41939:
          Type: Schedule
          Properties:
            Schedule: cron(0 3 * * ? *)
          Metadata:
            StackeryName: Every day at 3 am (UTC)
    Metadata:
      StackeryName: myCronJob
Parameters:
  StackeryStackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  StackeryEnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)
